# Generated by Django 4.0.3 on 2022-04-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tutorphonenumbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Tutor',
            new_name='CourseTutor',
        ),
        migrations.RenameModel(
            old_name='Student_Course_Tutor',
            new_name='StudentCourseTutor',
        ),
        migrations.RenameField(
            model_name='coursetutor',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursetutor',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentcoursetutor',
            old_name='course_tutor_id',
            new_name='course_tutor',
        ),
        migrations.RenameField(
            model_name='studentcoursetutor',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(related_name='courses', through='api.CourseTutor', to='api.tutor'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='api.StudentCourseTutor', to='api.coursetutor'),
        ),
        migrations.CreateModel(
            name='StudentPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.student')),
            ],
        ),
    ]
