# Generated by Django 4.0.3 on 2022-04-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_course_tutor_coursetutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='api.StudentCourseTutor', to='api.coursetutor'),
        ),
    ]
