# Generated by Django 4.0.3 on 2022-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
