# Generated by Django 4.0.4 on 2022-04-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
