# Generated by Django 4.0.4 on 2022-04-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tutor_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutors'},
        ),
    ]
