# Generated by Django 4.0.4 on 2022-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_course_options_alter_tutor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetutor',
            options={'verbose_name': 'Course-Tutor', 'verbose_name_plural': 'Courses-Tutors'},
        ),
        migrations.AlterModelOptions(
            name='money',
            options={'verbose_name': 'Money', 'verbose_name_plural': 'Money'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentcoursetutor',
            options={'verbose_name': 'Student and Course-Tutors', 'verbose_name_plural': 'Student and Course-Tutors'},
        ),
        migrations.AlterModelOptions(
            name='studentphonenumbers',
            options={'verbose_name': 'Student and his phone number', 'verbose_name_plural': 'Students and their phone numbers'},
        ),
        migrations.AlterModelOptions(
            name='tutorphonenumbers',
            options={'verbose_name': 'Phone number of some tutor', 'verbose_name_plural': 'Phone numbers of some tutors'},
        ),
        migrations.AddField(
            model_name='tutor',
            name='image_url',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
